require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customer_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CustomerRecord. As you add validations to CustomerRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CustomerRecord.create! valid_attributes
      get customer_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      customer_record = CustomerRecord.create! valid_attributes
      get customer_record_url(customer_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_customer_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      customer_record = CustomerRecord.create! valid_attributes
      get edit_customer_record_url(customer_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CustomerRecord" do
        expect {
          post customer_records_url, params: { customer_record: valid_attributes }
        }.to change(CustomerRecord, :count).by(1)
      end

      it "redirects to the created customer_record" do
        post customer_records_url, params: { customer_record: valid_attributes }
        expect(response).to redirect_to(customer_record_url(CustomerRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CustomerRecord" do
        expect {
          post customer_records_url, params: { customer_record: invalid_attributes }
        }.to change(CustomerRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post customer_records_url, params: { customer_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested customer_record" do
        customer_record = CustomerRecord.create! valid_attributes
        patch customer_record_url(customer_record), params: { customer_record: new_attributes }
        customer_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the customer_record" do
        customer_record = CustomerRecord.create! valid_attributes
        patch customer_record_url(customer_record), params: { customer_record: new_attributes }
        customer_record.reload
        expect(response).to redirect_to(customer_record_url(customer_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        customer_record = CustomerRecord.create! valid_attributes
        patch customer_record_url(customer_record), params: { customer_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer_record" do
      customer_record = CustomerRecord.create! valid_attributes
      expect {
        delete customer_record_url(customer_record)
      }.to change(CustomerRecord, :count).by(-1)
    end

    it "redirects to the customer_records list" do
      customer_record = CustomerRecord.create! valid_attributes
      delete customer_record_url(customer_record)
      expect(response).to redirect_to(customer_records_url)
    end
  end
end
